In [13]:
import pandas as pd
df = pd.read_csv('advertising.csv')
df.head(20)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0
5,59.99,23,59761.56,226.74,Sharable client-driven software,Jamieberg,1,Norway,2016-05-19 14:30:17,0
6,88.91,33,53852.85,208.36,Enhanced dedicated support,Brandonstad,0,Myanmar,2016-01-28 20:59:32,0
7,66.00,48,24593.33,131.76,Reactive local challenge,Port Jefferybury,1,Australia,2016-03-07 01:40:15,1
8,74.53,30,68862.00,221.51,Configurable coherent function,West Colin,1,Grenada,2016-04-18 09:33:42,0
9,69.88,20,55642.32,183.82,Mandatory homogeneous architecture,Ramirezton,1,Ghana,2016-07-11 01:42:51,0
10,47.64,49,45632.51,122.02,Centralized neutral neural-net,West Brandonton,0,Qatar,2016-03-16 20:19:01,1
11,83.07,37,62491.01,230.87,Team-oriented grid-enabled Local Area Network,East Theresashire,1,Burundi,2016-05-08 08:10:10,0
12,69.57,48,51636.92,113.12,Centralized content-based focus group,West Katiefurt,1,Egypt,2016-06-03 01:14:41,1
13,79.52,24,51739.63,214.23,Synergistic fresh-thinking array,North Tara,0,Bosnia and Herzegovina,2016-04-20 21:49:22,0
14,42.95,33,30976.00,143.56,Grass-roots coherent extranet,West William,0,Barbados,2016-03-24 09:31:49,1
15,63.45,23,52182.23,140.64,Persistent demand-driven interface,New Travistown,1,Spain,2016-03-09 03:41:30,1
16,55.39,37,23936.86,129.41,Customizable multi-tasking website,West Dylanberg,0,Palestinian Territory,2016-01-30 19:20:41,1
17,82.03,41,71511.08,187.53,Intuitive dynamic attitude,Pruittmouth,0,Afghanistan,2016-05-02 07:00:58,0
18,54.70,36,31087.54,118.39,Grass-roots solution-oriented conglomeration,Jessicastad,1,British Indian Ocean Territory (Chagos Archipe...,2016-02-13 07:53:55,1
19,74.58,40,23821.72,135.51,Advanced 24/7 productivity,Millertown,1,Russian Federation,2016-02-27 04:43:07,1

In [2]:
x = df.drop(['Ad Topic Line','City','Country','Clicked on Ad','Timestamp'],axis=1)
y = df['Clicked on Ad']
x.head()

   Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
0                     68.95   35     61833.90                256.09     0
1                     80.23   31     68441.85                193.77     1
2                     69.47   26     59785.94                236.50     0
3                     74.15   29     54806.18                245.89     1
4                     68.37   35     73889.99                225.58     0

In [3]:
from sklearn.linear_model import Lasso

In [4]:
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(x,y)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=5)

In [6]:
lasso_reg.score(x_test,y_test)

0.80945012674771

In [7]:
lasso_reg.score(x_train,y_train)

0.8281888839528877

In [8]:
import numpy as np
coeff_used = np.sum(lasso_reg.coef_!=0)
print(coeff_used)
print(df.columns[[0,1,2,3,6]][lasso_reg.coef_!=0])

4
Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage'],
      dtype='object')

In [9]:
x_new = df[df.columns[[0,1,2,3]]]
lasso_reg.fit(x_new,y)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_new,y,test_size=0.3,random_state=5)

In [11]:
lasso_reg.score(x_test,y_test)

0.80945012674771

In [12]:
lasso_reg.score(x_train,y_train)

0.8281888839528877